// packages/form/src/FormItem.jsx
/**
 * 字段类型
 * @type {Readonly<{number: string, input: string, boolean: string, textarea: string, "time-picker": string, "datetime-picker": string, "date-picker": string, "month-picker": string}>}
 */
const COLUMN_TYPE = Object.freeze({
  boolean: 'boolean',
  number: 'number',
  input: 'input',
  textarea: 'textarea',
  timePicker: 'time-picker',
  monthPicker: 'month-picker',
  datePicker: 'date-picker',
  datetimePicker: 'datetime-picker',
  radio: 'radio',
  radioButton: 'radio-button',
  select: 'select',
  // 滑动输入条
  slider: 'slider',
  rate: 'rate'
})

export default {
  name: 's-form-item',
  props: {
    column: {
      required: true,
      type: Object
    },
    label: String
  },
  methods: {
    getDecorator (column) {
      const decorator = [column.key]
      const option = {}
      // 获取校验规则
      const rules = this.getRules(column)
      if (rules) {
        option.rules = rules
      }
      // boolean处理
      if (column.type === 'boolean') {
        option.valuePropName = 'checked'
      }
      decorator.push(option)
      return decorator
    },
    getLabel () {
      return this.label ? this.label : this.column.label
    },
    /**
     * 获取提示语
     */
    getPlaceholder (column) {
      if (column.placeholder) {
        return column.placeholder
      } else {
        return '请输入' + column.label
      }
    },
    /**
     * 获取校验规则
     * @param column
     */
    getRules (column) {
      const rules = column.rules
      if (rules) {
        if (rules === true) {
          return [
            {
              required: true,
              message: '请输入' + column.label
            }
          ]
        } else {
          return rules
        }
      }
      return null
    }
  },
  render (h) {
    const { $slots, column, getDecorator, getPlaceholder, getLabel } = this
    return (
      <a-form-item
        {...{
          props: this.$attrs,
          on: this.$listeners
        }}
        label={getLabel()}>
        {
          (() => {
            if ($slots.default) {
              return $slots.default
            }
            switch (column.type) {
              case COLUMN_TYPE.boolean:
                return <a-switch v-decorator={getDecorator(column)} disabled={column.disabled}/>
              case COLUMN_TYPE.number:
                return <a-input-number v-decorator={getDecorator(column)} disabled={column.disabled}/>
              case COLUMN_TYPE.input:
                return <a-input placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled}/>
              case COLUMN_TYPE.textarea:
                return <a-textarea placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled}/>
              case COLUMN_TYPE.timePicker:
                return <a-time-picker placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled}/>
              case COLUMN_TYPE.monthPicker:
                return <a-month-picker placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled}/>
              case COLUMN_TYPE.slider: {
                // slider类型
                const sliderData = {}
                const dict = column.dict || []
                dict.forEach(({ key, value }) => {
                  sliderData[key] = value
                })
                return <a-slider placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled} marks={sliderData}/>
              }
              case COLUMN_TYPE.rate:
                return <a-rate v-decorator={getDecorator(column)} allowHalf={true} disabled={column.disabled}/>
            }
            if (column.type === COLUMN_TYPE.datePicker || column.type === COLUMN_TYPE.datetimePicker) {
              return <a-date-picker placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled} show-time={column.type === 'datetime-picker'}/>
            }
            // 遍历按钮组
            if (column.type === COLUMN_TYPE.radio || column.type === COLUMN_TYPE.radioButton) {
              const dict = column.dict || []
              return <a-radio-group v-decorator={getDecorator(column)} disabled={column.disabled}>
                {
                  dict.map(({ key, value, disabled }) => {
                    if (column.type === COLUMN_TYPE.radio) {
                      return <a-radio key={key} disabled={disabled === true} value={key}>{value}</a-radio>
                    } else {
                      return <a-radio-button key={key} disabled={disabled === true} value={key}>{value}</a-radio-button>
                    }
                  })
                }
              </a-radio-group>
            }
            // select 类型
            if (column.type === COLUMN_TYPE.select) {
              const dict = column.dict || []
              return <a-select allowClear={true} placeholder={getPlaceholder(column)} v-decorator={getDecorator(column)} disabled={column.disabled}>
                {
                  dict.map(({ key, value, disabled }) => {
                    return <a-select-option value={key}>
                      {value}
                    </a-select-option>
                  })
                }
              </a-select>
            }
          })()
        }
      </a-form-item>
    )
  }
}

// packages/form/src/FormItem.tsx
import { defineComponent, PropType } from 'vue'

import { FormColumn } from '../../Types'

const COLUMN_TYPE: {[index: string]: string} = Object.freeze({
  boolean: 'boolean',
  number: 'number',
  input: 'input',
  textarea: 'textarea',
  timePicker: 'time-picker',
  monthPicker: 'month-picker',
  datePicker: 'date-picker',
  datetimePicker: 'datetime-picker',
  radio: 'radio',
  radioButton: 'radio-button',
  select: 'select',
  // 滑动输入条
  slider: 'slider',
  rate: 'rate'
})

/**
 * s-form-item 组件
 * @author shizhongming
 * @since 2.0
 * 2020-10-07 11:05
 */
export default defineComponent({
  name: 'SFormItem',
  props: {
    column: {
      type: Object as PropType<FormColumn>,
      required: true
    },
    label: {
      type: String as PropType<string>
    },
    value: {}
  },
  methods: {
    /**
     * 获取label
     */
    getLabel (): string | undefined {
      return this.label ? this.label : this.column.label
    },
    /**
     * 获取提示信息
     * @param column
     */
    getPlaceholder (column: FormColumn): string {
      const { placeholder, label } = column
      if (placeholder) {
        return placeholder
      }
      return '请输入' + label
    },
    /**
     * 值改变触发
     * @param column
     * @param value
     */
    handleChange (column: FormColumn, value: any) {
      this.$emit('value-change', value)
      this.$emit('update:value', value)
    }
  },
  render () {
    const props = this.$attrs
    const column = this.column
    const { getLabel, $slots, getPlaceholder, handleChange } = this
    return (
      <a-form-item
        {...props}
        name={column.key}
        label={getLabel()}>
        {
          (() => {
            if ($slots.default) {
              return $slots.default()
            }
            switch (column.type) {
              case COLUMN_TYPE.boolean:
                return <a-switch onInput={(value: any) => handleChange(column, value)} value={this.value} disabled={column.disabled}/>
              case COLUMN_TYPE.input:
                return <a-input onInput={(e: any) => handleChange(column, e.target.value)} placeholder={getPlaceholder(column)} value={this.value} disabled={column.disabled}/>
            }
          })()
        }
      </a-form-item>
    )
  }
})
